version: 0.0
os: linux
files:
  - source: /
    destination: /var/app
hooks:
  ApplicationStop:
    - location: scripts/1_ApplicationStop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/2_BeforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/3_AfterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/4_ApplicationStart.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/5_ValidateService.sh
      runas: root
